[aw-qt]
autostart_modules = ["aw-server", "aw-watcher-afk", "aw-watcher-window","aw-watcher-input","aw-watcher-media-player"]

[aw-qt-testing]
#autostart_modules = ["aw-server", "aw-watcher-afk", "aw-watcher-window"]
