    require "user.options"
    require "user.keymaps"
    require "user.plugins"
    require "user.colorscheme"
    require "user.treesitter"
    require "user.telescope"
    require "user.bufferline"
    require "user.indentline"
    require "user.comment"
    require "user.cmp"
    require "user.lsp"
    require "user.autopairs"
    -- require "user.iron"
    require "user.nnn"
    -- require "user.gitsigns"
    -- require "user.nvim-tree"
    -- require 'user.dap'
    -- require 'user.dapui'
    -- require 'user.dapvirtual'
    -- require "user.toggleterm"
    -- require "user.project"
    -- require "user.impatient"
    -- require "user.alpha"
    -- require "user.whichkey"
    -- require "user.autocommands"
    -- require "user.taskwiki"
